### ISSUE TITLE
Get Event details

### ISSUE THREAD

**Issue by c4n1** [Owlz/winevt#2]
I can work out how to navigate getting data from the XML but can't see how to to get the details from an event i.e. the description you can see in event viewer.  Is this possible?

**Comment by bannsec** [comment]
The textual representation (for example, the "general" tab) for a given EventID is not available through this atm. I've been poking around trying to figure out exactly where that comes from, and so far the best I can tell is that it actually involves loading up a DLL for each source provider and calling a format function from it. If that's the case, that seems very dirty.

**Comment by c4n1** [comment]
Yup that seems excessive, thanks for the quick reply.

**Comment by bannsec** [comment]
Np
